--- #YAML:1.0
name:               File-Rsync
version:            0.43
abstract:           Wrapper module for rsync(1) http://rsync.samba.org/
author:
    - Lee Eakin <leakin@dfw.nostrum.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Scalar::Util:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
